# 使用 SageMaker 进行超参优化
在超参优化的过程中，可能会存在多个局部高低点，不同的超参数也可能存在不同的寻优路径。SageMaker 本身提供了贝叶斯超参优化的功能，这对于一些超参数量多、模型复杂、不适合网格搜索的场景非常试用。SageMaker 超参优化可以在几百次尝试之内快速找到一组对应局部的高低点超参。

这部分实验将展示如何定义一个 SageMaker 超参优化任务，并快速找到交易策略（以双均线策略为例）历史上的最优参数组合。

In [ ]:
### 定义参数

我们首先定义环境变量：

In [9]:
import boto3

aws_account_id = boto3.client('sts').get_caller_identity().get('Account')
repository_name = 'sagemaker-hpo'
aws_region = 'us-east-1'
my_name = 'sailong-demo'
bucket = 'algo-trading-workshop-{}'.format(my_name)

ecr = boto3.client('ecr', region_name=aws_region)
s3 = boto3.client('s3', region_name=aws_region)

### 获取数据

定义一个函数，通过 Athena 获取行情数据：

In [10]:
!pip install awswrangler

import awswrangler as wr

s3_output = wr.athena.create_athena_bucket()

def execute_query(database, sql):
    
    query_execution_id = wr.athena.start_query_execution(database=database, sql=sql)
    response = wr.athena.get_query_execution(query_execution_id=query_execution_id)
    wr.athena.wait_query(query_execution_id=query_execution_id)
    OutputLocation = response['ResultConfiguration']['OutputLocation']
    
    return OutputLocation

Requirement already satisfied: awswrangler in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (2.10.0)
Requirement already satisfied: pymysql<1.1.0,>=0.9.0 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from awswrangler) (1.0.2)
Requirement already satisfied: boto3<2.1.0,>=1.16.8 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from awswrangler) (1.17.100)
Requirement already satisfied: numpy<2.1.0,>=1.18.0 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from awswrangler) (1.19.5)
Requirement already satisfied: pandas<2.1.0,>=1.1.0 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from awswrangler) (1.1.5)
Requirement already satisfied: pyarrow<4.1.0,>=2.0.0 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from awswrangler) (4.0.1)
Requirement already satisfied: botocore<2.1.0,>=1.19.8 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from awswrangler) (1.20.100)
Requirement already satisfied: redshift-connector~=2.0.882 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from awswrangler) (2.0.884)
Requirement already satisfied: pg8000<1.21.0,>=1.16.0 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from awswrangler) (1.20.0)
Requirement already satisfied: openpyxl~=3.0.0 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from awswrangler) (3.0.6)
Requirement already satisfied: s3transfer<0.5.0,>=0.4.0 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from boto3<2.1.0,>=1.16.8->awswrangler) (0.4.2)
Requirement already satisfied: jmespath<1.0.0,>=0.7.1 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from boto3<2.1.0,>=1.16.8->awswrangler) (0.10.0)
Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from botocore<2.1.0,>=1.19.8->awswrangler) (2.8.1)
Requirement already satisfied: urllib3<1.27,>=1.25.4 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from botocore<2.1.0,>=1.19.8->awswrangler) (1.26.5)
Requirement already satisfied: et-xmlfile in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from openpyxl~=3.0.0->awswrangler) (1.0.1)
Requirement already satisfied: jdcal in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from openpyxl~=3.0.0->awswrangler) (1.4.1)
Requirement already satisfied: pytz>=2017.2 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from pandas<2.1.0,>=1.1.0->awswrangler) (2021.1)
Requirement already satisfied: scramp>=1.4.0 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from pg8000<1.21.0,>=1.16.0->awswrangler) (1.4.0)
Requirement already satisfied: six>=1.5 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from python-dateutil<3.0.0,>=2.1->botocore<2.1.0,>=1.19.8->awswrangler) (1.15.0)
Requirement already satisfied: requests<2.25.2,>=2.23.0 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from redshift-connector~=2.0.882->awswrangler) (2.25.1)
Requirement already satisfied: beautifulsoup4<5.0.0,>=4.7.0 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from redshift-connector~=2.0.882->awswrangler) (4.9.3)
Requirement already satisfied: lxml>=4.6.2 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from redshift-connector~=2.0.882->awswrangler) (4.6.3)
Requirement already satisfied: packaging in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from redshift-connector~=2.0.882->awswrangler) (20.9)
Requirement already satisfied: soupsieve>1.2 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from beautifulsoup4<5.0.0,>=4.7.0->redshift-connector~=2.0.882->awswrangler) (2.0.1)
Requirement already satisfied: certifi>=2017.4.17 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from requests<2.25.2,>=2.23.0->redshift-connector~=2.0.882->awswrangler) (2021.5.30)
Requirement already satisfied: idna<3,>=2.5 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from requests<2.25.2,>=2.23.0->redshift-connector~=2.0.882->awswrangler) (2.10)
Requirement already satisfied: chardet<5,>=3.0.2 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from requests<2.25.2,>=2.23.0->redshift-connector~=2.0.882->awswrangler) (3.0.4)
Requirement already satisfied: asn1crypto==1.4.0 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from scramp>=1.4.0->pg8000<1.21.0,>=1.16.0->awswrangler) (1.4.0)
Requirement already satisfied: pyparsing>=2.0.2 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from packaging->redshift-connector~=2.0.882->awswrangler) (2.4.7)
WARNING: You are using pip version 21.1.2; however, version 21.2.3 is available.
You should consider upgrading via the '/home/ec2-user/anaconda3/envs/python3/bin/python -m pip install --upgrade pip' command.

In [11]:
database = 'stock-data'
table = 'stock_day'
fields = '*'
ticker = '600519'
orderby = 'tradedate'
sort = 'ASC'

sql = f'''
SELECT {fields}
FROM "{database}"."{table}"
WHERE ticker='{ticker}'
AND tradedate>='2019-01-01'
ORDER BY {orderby}
{sort}
'''

output_location = execute_query(database, sql)
print(output_location)

s3://aws-athena-query-results-661060674358-us-east-1/e17cef9a-cd46-4ea4-ac9c-683c31f239d6.csv

In [12]:
df = wr.s3.read_csv(path=[output_location])

df['ticker'] = df['ticker'].apply(lambda x: str(x))
df['ticker'] = df['ticker'].apply(lambda x: '0'*(6-len(x)) + x)
df['openprice'] = df['openprice'] * df['accumadjfactor'] / df['accumadjfactor'].iloc[-1]
df['closeprice'] = df['closeprice'] * df['accumadjfactor'] / df['accumadjfactor'].iloc[-1]
df['highestprice'] = df['highestprice'] * df['accumadjfactor'] / df['accumadjfactor'].iloc[-1]
df['lowestprice'] = df['lowestprice'] * df['accumadjfactor'] / df['accumadjfactor'].iloc[-1]
df = df[df['isopen'] == True]
df.drop('isopen', 1, inplace=True)
df.drop('accumadjfactor', 1, inplace=True)
df.set_index('tradedate', inplace=True)
df.sort_index(0, inplace=True)

df.rename(columns={'openprice': 'open'}, inplace=True)
df.rename(columns={'closeprice': 'close'}, inplace=True)
df.rename(columns={'highestprice': 'high'}, inplace=True)
df.rename(columns={'lowestprice': 'low'}, inplace=True)
df.rename(columns={'turnovervol': 'volume'}, inplace=True)
df['openinterest'] = 0 # A股回测中一般并不考虑利率，通常可以直接设为 0
df.head()

,ticker,secid,open,high,low,close,volume,turnovervalue,openinterest
tradedate,,,,,,,,,
2019-01-02,600519,600519.SH,588.598322,590.547514,574.153066,577.983905,6228649.0,3.754388e+09,0
2019-01-03,600519,600519.SH,578.939203,580.569963,565.265905,569.318682,3097735.0,1.838179e+09,0
2019-01-04,600519,600519.SH,566.694027,586.369294,561.618406,580.898045,3768347.0,2.258501e+09,0
2019-01-07,600519,600519.SH,586.687727,590.547514,581.110333,584.265710,3475013.0,2.105981e+09,0
2019-01-08,600519,600519.SH,584.275359,590.547514,579.238336,583.590247,2883813.0,1.750413e+09,0

将结果保存在这个实验专用的路径下，这个路径还将用于保存批量任务的输入和输出结果：

In [13]:
wr.s3.to_csv(df=df, path='s3://{}/{}/data.csv'.format(bucket, repository_name))

{'paths': ['s3://algo-trading-workshop-sailong-demo/sagemaker-hpo/data.csv'],
 'partitions_values': {}}

### 定义回测任务

使用 SageMaker 运行任务时，默认使用 /opt/ml/ 路径。任务运行时会默认运行 /opt/ml/code/ 路径下的 train 文件。因此我们需要对回测代码做一些简单改写：

In [16]:
! mkdir {repository_name}
! mkdir {repository_name}/model

In [18]:
%%writefile {repository_name}/model/train
#!/usr/bin/env python
from __future__ import (absolute_import, division, print_function,
                        unicode_literals)
from datetime import datetime
import json
import numpy as np
import pandas as pd
import os.path
import sys

import backtrader as bt

# 这里定义 SageMaker 任务默认的环境路径
prefix = '/opt/ml/'

config_path = os.path.join(prefix, 'input/config')
input_path = os.path.join(prefix, 'input/data/training')
data_path = os.path.join(input_path, 'data.csv')
output_path = os.path.join(prefix, 'output')
model_path = os.path.join(prefix, 'model')


class MyStrategy(bt.Strategy):
    ## 全局参数
    params=(('fastmaperiod', 10),
            ('slowmaperiod', 30),
            ('printlog', False),)

    ## 策略初始化
    def __init__(self):

        # 初始化交易指令、买卖价格和手续费
        self.order = None
        self.buyprice = None
        self.buycomm = None

        # 添加移动均线指标。Backtrader 集成了 talib，可以自动算出一些常见的技术指标
        self.fastma = bt.indicators.SimpleMovingAverage(self.datas[0], period=self.params.fastmaperiod)
        self.slowma = bt.indicators.SimpleMovingAverage(self.datas[0], period=self.params.slowmaperiod)
        
    ## 策略核心逻辑
    def next(self):
        # 记录收盘价
#         self.log('收盘价：%.2f' % self.datas[0].close[0])
        if self.order: # 检查是否有指令等待执行
            return
        # 检查是否持仓   
        if not self.position: # 如果没有持仓
            # 快线上穿慢线，执行买入
            if self.fastma[0] > self.slowma[0]:
                self.log('买入委托：%.2f' % self.datas[0].close[0])
                #执行买入
                self.size = int(self.broker.cash / self.datas[0].close[0])
                self.order = self.buy(size=self.size)
        else: # 
            # 快线下穿慢线，执行卖出
            if self.fastma[0] < self.slowma[0]:
                self.log('卖出委托：%.2f' % self.datas[0].close[0])
                #执行卖出
                self.order = self.sell(size=self.size)

    ## 4、日志记录
    # 交易记录日志（可选，默认不输出结果）
    def log(self, txt, dt=None, doprint=False):
        if self.params.printlog or doprint:
            dt = dt or self.datas[0].datetime.date(0)
            print(f'{dt.isoformat()},{txt}')

    # 记录交易执行情况（可选，默认不输出结果）
    def notify_order(self, order):
        # 如果 order 为 submitted/accepted，返回空
        if order.status in [order.Submitted, order.Accepted]:
            return
        # 如果 order 为 buy/sell executed，报告价格结果
        if order.status in [order.Completed]: 
            if order.isbuy():
                self.log(f'买入：\n价格：%.2f,\
                交易金额：-%.2f,\
                手续费：%.2f' % (order.executed.price, order.executed.value, order.executed.comm))
                self.buyprice = order.executed.price
                self.buycomm = order.executed.comm
            else:
                self.log(f'卖出:\n价格：%.2f,\
                交易金额：%.2f,\
                手续费：%.2f' % (order.executed.price, order.executed.price*self.size, order.executed.comm))
            self.bar_executed = len(self) 

        # 如果指令取消/交易失败, 报告结果
        elif order.status in [order.Canceled, order.Margin, order.Rejected]:
            self.log('交易失败')
        self.order = None

    # 记录交易收益情况（可省略，默认不输出结果）
    def notify_trade(self,trade):
        if not trade.isclosed:
            return
        self.log(f'策略收益：\n毛收益 {trade.pnl:.2f}, 净收益 {trade.pnlcomm:.2f}')

    # 回测结束后输出结果（可省略，默认输出结果）
    def stop(self):
        self.log('(MA均线： %2d日  %2d日) 期末总资金 %.2f' %
                 (self.params.fastmaperiod, self.params.slowmaperiod, self.broker.getvalue()), doprint=True)

        
if __name__ == '__main__':
    
    # 创建 Cerebro 对象
    cerebro = bt.Cerebro()

    df = pd.read_csv(data_path)
    df.set_index('tradedate', inplace=True)
    
    # 创建 Data Feed
    df.index = pd.to_datetime(df.index)
    start = df.index[0]
    end = df.index[-1]
    print(start, '-', end)
    data = bt.feeds.PandasData(dataname=df, fromdate=start, todate=end)
    # 将 Data Feed 添加至 Cerebro
    cerebro.adddata(data)

    # 添加策略 Cerebro
    try:
        with open("{}/hyperparameters.json".format(config_path)) as json_file:
            params = json.load(json_file)
        print('Parameter load success')
    except Exception as e:
        print(e)
    cerebro.addstrategy(MyStrategy, fastmaperiod=int(params['fastmaperiod']), slowmaperiod=int(params['slowmaperiod']), printlog=True)
    
    # 设置初始资金
    cerebro.broker.setcash(100000.0)
    # 设置手续费为万二
    cerebro.broker.setcommission(commission=0.0002) 

    # 在开始时 print 初始账户价值
    print('Starting Portfolio Value: %.2f' % cerebro.broker.getvalue())

    # 运行回测流程
    cerebro.run()

    # 在结束时 print 最终账户价值
    print('Final Portfolio Value: %.2f' % cerebro.broker.getvalue())
    print('Return: %.4f' % (float(cerebro.broker.getvalue())/1e5 - 1))

    sys.exit(0)

Writing sagemaker-hpo/model/train

### 创建镜像仓库和容器镜像

接下来构建一个 python3 容器镜像和镜像仓库：

In [20]:
ecr.create_repository(repositoryName=repository_name)

RepositoryAlreadyExistsException: An error occurred (RepositoryAlreadyExistsException) when calling the CreateRepository operation: The repository with name 'sagemaker-hpo' already exists in the registry with id '661060674358'

In [21]:
%%writefile {repository_name}/Dockerfile
FROM python:3.8

RUN pip --no-cache-dir install \
    backtrader\
    boto3 \
    pandas

ENV PYTHONUNBUFFERED=TRUE
ENV PYTHONDONTWRITEBYTECODE=TRUE
ENV PATH="/opt/ml/code:${PATH}"

RUN mkdir -p /opt/ml/input/data
RUN mkdir -p /opt/ml/input/config
RUN mkdir -p /opt/ml/code
RUN mkdir -p /opt/ml/failure
RUN mkdir -p /opt/ml/model
RUN mkdir -p /opt/ml/output

COPY model /opt/ml/code
RUN chmod -R 777 /opt/ml/code
WORKDIR /opt/ml/code

Writing sagemaker-hpo/Dockerfile

In [22]:
!docker build {repository_name} -t {repository_name}

Sending build context to Docker daemon  9.216kB
Step 1/14 : FROM python:3.8
3.8: Pulling from library/python

765e08d1: Pulling fs layer
670e5e55: Pulling fs layer
180f4992: Pulling fs layer
209566d0: Pulling fs layer
44ed766e: Pulling fs layer
520e0e66: Pulling fs layer
83039b08: Pulling fs layer
94c24f54: Pulling fs layer
Digest: sha256:caa7d8d6bfaa181f30c5a5074b81b6963246615f0140dca1d86e1e98efa99dc6[9A
Status: Downloaded newer image for python:3.8
 ---> 1d136c1ca7e1
Step 2/14 : RUN pip --no-cache-dir install     backtrader    boto3     pandas
 ---> Running in 9c7e9909dd48
Collecting backtrader
  Downloading backtrader-1.9.76.123-py2.py3-none-any.whl (410 kB)
Collecting boto3
  Downloading boto3-1.18.16-py3-none-any.whl (131 kB)
Collecting pandas
  Downloading pandas-1.3.1-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (11.7 MB)
Collecting jmespath<1.0.0,>=0.7.1
  Downloading jmespath-0.10.0-py2.py3-none-any.whl (24 kB)
Collecting s3transfer<0.6.0,>=0.5.0
  Downloading s3transfer-0.5.0-py3-none-any.whl (79 kB)
Collecting botocore<1.22.0,>=1.21.16
  Downloading botocore-1.21.16-py3-none-any.whl (7.8 MB)
Collecting numpy>=1.17.3
  Downloading numpy-1.21.1-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (15.8 MB)
Collecting python-dateutil>=2.7.3
  Downloading python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
Collecting pytz>=2017.3
  Downloading pytz-2021.1-py2.py3-none-any.whl (510 kB)
Collecting urllib3<1.27,>=1.25.4
  Downloading urllib3-1.26.6-py2.py3-none-any.whl (138 kB)
Collecting six>=1.5
  Downloading six-1.16.0-py2.py3-none-any.whl (11 kB)
Installing collected packages: six, urllib3, python-dateutil, jmespath, botocore, s3transfer, pytz, numpy, pandas, boto3, backtrader
Successfully installed backtrader-1.9.76.123 boto3-1.18.16 botocore-1.21.16 jmespath-0.10.0 numpy-1.21.1 pandas-1.3.1 python-dateutil-2.8.2 pytz-2021.1 s3transfer-0.5.0 six-1.16.0 urllib3-1.26.6
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
Removing intermediate container 9c7e9909dd48
 ---> e7b39bea9016
Step 3/14 : ENV PYTHONUNBUFFERED=TRUE
 ---> Running in 1a5d8882d00e
Removing intermediate container 1a5d8882d00e
 ---> 11ad55b890eb
Step 4/14 : ENV PYTHONDONTWRITEBYTECODE=TRUE
 ---> Running in 5630071f4870
Removing intermediate container 5630071f4870
 ---> 547f52870bae
Step 5/14 : ENV PATH="/opt/ml/code:${PATH}"
 ---> Running in f311a7a9bb88
Removing intermediate container f311a7a9bb88
 ---> ba179eb60025
Step 6/14 : RUN mkdir -p /opt/ml/input/data
 ---> Running in 1773ee9352a3
Removing intermediate container 1773ee9352a3
 ---> 207d6c6473e4
Step 7/14 : RUN mkdir -p /opt/ml/input/config
 ---> Running in c92ca91375b1
Removing intermediate container c92ca91375b1
 ---> abc49529582f
Step 8/14 : RUN mkdir -p /opt/ml/code
 ---> Running in 496bc963f9d1
Removing intermediate container 496bc963f9d1
 ---> 0fdd9541fcc2
Step 9/14 : RUN mkdir -p /opt/ml/failure
 ---> Running in 69727eb2454c
Removing intermediate container 69727eb2454c
 ---> f60df9fb483c
Step 10/14 : RUN mkdir -p /opt/ml/model
 ---> Running in 48c1a864fce9
Removing intermediate container 48c1a864fce9
 ---> 0f11dd8a1d60
Step 11/14 : RUN mkdir -p /opt/ml/output
 ---> Running in 79cfa88f7b2d
Removing intermediate container 79cfa88f7b2d
 ---> 3689d98da81c
Step 12/14 : COPY model /opt/ml/code
 ---> b5c922aae3ab
Step 13/14 : RUN chmod -R 777 /opt/ml/code
 ---> Running in 11950752d278
Removing intermediate container 11950752d278
 ---> f4dc8760d80d
Step 14/14 : WORKDIR /opt/ml/code
 ---> Running in d7c1b9453361
Removing intermediate container d7c1b9453361
 ---> 11ae0ba7d82c
Successfully built 11ae0ba7d82c
Successfully tagged sagemaker-hpo:latest

SageMaker 提供了本地测试功能。在提交 HPO 任务之前，可以先在本地尝试运行镜像：

In [23]:
!pip uninstall -y sagemaker
!pip install sagemaker==1.72.0
import sagemaker
from sagemaker.estimator import Estimator

role = sagemaker.get_execution_role()
session = sagemaker.Session()

Found existing installation: sagemaker 2.45.0
Uninstalling sagemaker-2.45.0:
  Successfully uninstalled sagemaker-2.45.0
Collecting sagemaker==1.72.0
  Downloading sagemaker-1.72.0.tar.gz (297 kB)
     |████████████████████████████████| 297 kB 32.3 MB/s eta 0:00:01
Requirement already satisfied: boto3>=1.14.12 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from sagemaker==1.72.0) (1.17.100)
Requirement already satisfied: numpy>=1.9.0 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from sagemaker==1.72.0) (1.19.5)
Requirement already satisfied: protobuf>=3.1 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from sagemaker==1.72.0) (3.15.2)
Requirement already satisfied: scipy>=0.19.0 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from sagemaker==1.72.0) (1.5.3)
Requirement already satisfied: protobuf3-to-dict>=0.1.5 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from sagemaker==1.72.0) (0.1.5)
Collecting smdebug-rulesconfig==0.1.4
  Downloading smdebug_rulesconfig-0.1.4-py2.py3-none-any.whl (10 kB)
Requirement already satisfied: importlib-metadata>=1.4.0 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from sagemaker==1.72.0) (3.7.0)
Requirement already satisfied: packaging>=20.0 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from sagemaker==1.72.0) (20.9)
Requirement already satisfied: botocore<1.21.0,>=1.20.100 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from boto3>=1.14.12->sagemaker==1.72.0) (1.20.100)
Requirement already satisfied: s3transfer<0.5.0,>=0.4.0 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from boto3>=1.14.12->sagemaker==1.72.0) (0.4.2)
Requirement already satisfied: jmespath<1.0.0,>=0.7.1 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from boto3>=1.14.12->sagemaker==1.72.0) (0.10.0)
Requirement already satisfied: urllib3<1.27,>=1.25.4 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from botocore<1.21.0,>=1.20.100->boto3>=1.14.12->sagemaker==1.72.0) (1.26.5)
Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from botocore<1.21.0,>=1.20.100->boto3>=1.14.12->sagemaker==1.72.0) (2.8.1)
Requirement already satisfied: typing-extensions>=3.6.4 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from importlib-metadata>=1.4.0->sagemaker==1.72.0) (3.7.4.3)
Requirement already satisfied: zipp>=0.5 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from importlib-metadata>=1.4.0->sagemaker==1.72.0) (3.4.0)
Requirement already satisfied: pyparsing>=2.0.2 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from packaging>=20.0->sagemaker==1.72.0) (2.4.7)
Requirement already satisfied: six>=1.9 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from protobuf>=3.1->sagemaker==1.72.0) (1.15.0)
Building wheels for collected packages: sagemaker
  Building wheel for sagemaker (setup.py) ... done
  Created wheel for sagemaker: filename=sagemaker-1.72.0-py2.py3-none-any.whl size=386358 sha256=fb60f316075ae7793011793cb516b1d0e2bf2cf93ef66978f56baa92abd4d0cf
  Stored in directory: /home/ec2-user/.cache/pip/wheels/c3/58/70/85faf4437568bfaa4c419937569ba1fe54d44c5db42406bbd7
Successfully built sagemaker
Installing collected packages: smdebug-rulesconfig, sagemaker
  Attempting uninstall: smdebug-rulesconfig
    Found existing installation: smdebug-rulesconfig 1.0.1
    Uninstalling smdebug-rulesconfig-1.0.1:
      Successfully uninstalled smdebug-rulesconfig-1.0.1
Successfully installed sagemaker-1.72.0 smdebug-rulesconfig-0.1.4
WARNING: You are using pip version 21.1.2; however, version 21.2.3 is available.
You should consider upgrading via the '/home/ec2-user/anaconda3/envs/python3/bin/python -m pip install --upgrade pip' command.

Exception ignored in: <bound method _S3ObjectBase.__del__ of <awswrangler.s3._fs._S3ObjectBase object at 0x7fc66ec23400>>
Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/awswrangler/s3/_fs.py", line 305, in __del__
    self.close()
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/awswrangler/s3/_fs.py", line 545, in close
    function_name="put_object", s3_additional_kwargs=self._s3_additional_kwargs
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/awswrangler/_utils.py", line 331, in try_it
    return f(**kwargs)
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/botocore/client.py", line 386, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/botocore/client.py", line 692, in _make_api_call
    operation_model, request_dict, request_context)
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/botocore/client.py", line 711, in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/botocore/endpoint.py", line 102, in make_request
    return self._send_request(request_dict, operation_model)
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/botocore/endpoint.py", line 132, in _send_request
    request = self.create_request(request_dict, operation_model)
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/botocore/endpoint.py", line 116, in create_request
    operation_name=operation_model.name)
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/botocore/hooks.py", line 356, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/botocore/hooks.py", line 228, in emit
    return self._emit(event_name, kwargs)
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/botocore/hooks.py", line 211, in _emit
    response = handler(**kwargs)
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/botocore/signers.py", line 90, in handler
    return self.sign(operation_name, request)
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/botocore/signers.py", line 128, in sign
    operation_name, signing_type, request.context)
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/botocore/signers.py", line 185, in _choose_signer
    handler, response = self._event_emitter.emit_until_response(
ReferenceError: weakly-referenced object no longer exists

In [24]:
# 默认参数
params = { 
    'fastmaperiod': 6,
    'slowmaperiod': 11
}

estimator = Estimator(
    repository_name,
    role=role,
    train_instance_count=1,
    train_instance_type='local',
    output_path='s3://{}/{}/output'.format(bucket, repository_name),
    base_job_name=repository_name, 
    hyperparameters=params,
)

estimator.fit('s3://{}/{}/data.csv'.format(bucket, repository_name))

Parameter image_name will be renamed to image_uri in SageMaker Python SDK v2.
's3_input' class will be renamed to 'TrainingInput' in SageMaker Python SDK v2.

Creating tmppdbkowxv_algo-1-vepgd_1 ...
Creating tmppdbkowxv_algo-1-vepgd_1 ... done
Attaching to tmppdbkowxv_algo-1-vepgd_1
algo-1-vepgd_1  | 2019-01-02 00:00:00 - 2021-07-05 00:00:00
algo-1-vepgd_1  | Parameter load success
algo-1-vepgd_1  | Starting Portfolio Value: 100000.00
algo-1-vepgd_1  | 2019-01-16,买入委托：637.93
algo-1-vepgd_1  | 2019-01-17,买入：
algo-1-vepgd_1  | 价格：639.76,                交易金额：-99802.53,                手续费：19.96
algo-1-vepgd_1  | 2019-02-26,卖出委托：701.85
algo-1-vepgd_1  | 2019-02-27,卖出:
algo-1-vepgd_1  | 价格：707.31,                交易金额：110339.75,                手续费：22.07
algo-1-vepgd_1  | 2019-02-27,策略收益：
algo-1-vepgd_1  | 毛收益 10537.22, 净收益 10495.19
algo-1-vepgd_1  | 2019-02-28,买入委托：728.54
algo-1-vepgd_1  | 2019-03-01,交易失败
algo-1-vepgd_1  | 2019-03-01,买入委托：761.63
algo-1-vepgd_1  | 2019-03-04,交易失败
algo-1-vepgd_1  | 2019-03-04,买入委托：754.45
algo-1-vepgd_1  | 2019-03-05,交易失败
algo-1-vepgd_1  | 2019-03-05,买入委托：752.45
algo-1-vepgd_1  | 2019-03-06,买入：
algo-1-vepgd_1  | 价格：747.83,                交易金额：-109183.74,                手续费：21.84
algo-1-vepgd_1  | 2019-03-12,卖出委托：718.90
algo-1-vepgd_1  | 2019-03-13,卖出:
algo-1-vepgd_1  | 价格：719.37,                交易金额：105027.72,                手续费：21.01
algo-1-vepgd_1  | 2019-03-13,策略收益：
algo-1-vepgd_1  | 毛收益 -4156.03, 净收益 -4198.87
algo-1-vepgd_1  | 2019-03-18,买入委托：781.69
algo-1-vepgd_1  | 2019-03-19,买入：
algo-1-vepgd_1  | 价格：774.85,                交易金额：-104605.07,                手续费：20.92
algo-1-vepgd_1  | 2019-03-28,卖出委托：778.52
algo-1-vepgd_1  | 2019-03-29,卖出:
algo-1-vepgd_1  | 价格：805.73,                交易金额：108773.64,                手续费：21.75
algo-1-vepgd_1  | 2019-03-29,策略收益：
algo-1-vepgd_1  | 毛收益 4168.57, 净收益 4125.89
algo-1-vepgd_1  | 2019-03-29,买入委托：824.06
algo-1-vepgd_1  | 2019-04-01,买入：
algo-1-vepgd_1  | 价格：829.85,                交易金额：-110370.63,                手续费：22.07
algo-1-vepgd_1  | 2019-05-06,卖出委托：874.24
algo-1-vepgd_1  | 2019-05-07,卖出:
algo-1-vepgd_1  | 价格：861.97,                交易金额：114641.72,                手续费：22.93
algo-1-vepgd_1  | 2019-05-07,策略收益：
algo-1-vepgd_1  | 毛收益 4271.09, 净收益 4226.08
algo-1-vepgd_1  | 2019-05-17,买入委托：875.00
algo-1-vepgd_1  | 2019-05-20,交易失败
algo-1-vepgd_1  | 2019-05-20,买入委托：853.94
algo-1-vepgd_1  | 2019-05-21,买入：
algo-1-vepgd_1  | 价格：853.98,                交易金额：-114433.06,                手续费：22.89
algo-1-vepgd_1  | 2019-05-23,卖出委托：830.82
algo-1-vepgd_1  | 2019-05-24,卖出:
algo-1-vepgd_1  | 价格：834.68,                交易金额：111847.00,                手续费：22.37
algo-1-vepgd_1  | 2019-05-24,策略收益：
algo-1-vepgd_1  | 毛收益 -2586.06, 净收益 -2631.31
algo-1-vepgd_1  | 2019-05-31,买入委托：858.80
algo-1-vepgd_1  | 2019-06-03,买入：
algo-1-vepgd_1  | 价格：860.73,                交易金额：-111895.24,                手续费：22.38
algo-1-vepgd_1  | 2019-06-06,卖出委托：831.91
algo-1-vepgd_1  | 2019-06-10,卖出:
algo-1-vepgd_1  | 价格：827.91,                交易金额：107627.67,                手续费：21.53
algo-1-vepgd_1  | 2019-06-10,策略收益：
algo-1-vepgd_1  | 毛收益 -4267.57, 净收益 -4311.48
algo-1-vepgd_1  | 2019-06-14,买入委托：881.00
algo-1-vepgd_1  | 2019-06-17,买入：
algo-1-vepgd_1  | 价格：875.21,                交易金额：-106775.24,                手续费：21.36
algo-1-vepgd_1  | 2019-07-10,卖出委托：962.12
algo-1-vepgd_1  | 2019-07-11,卖出:
algo-1-vepgd_1  | 价格：969.41,                交易金额：118267.49,                手续费：23.65
algo-1-vepgd_1  | 2019-07-11,策略收益：
algo-1-vepgd_1  | 毛收益 11492.25, 净收益 11447.25
algo-1-vepgd_1  | 2019-07-30,买入委托：958.60
algo-1-vepgd_1  | 2019-07-31,买入：
algo-1-vepgd_1  | 价格：954.76,                交易金额：-118389.78,                手续费：23.68
algo-1-vepgd_1  | 2019-08-06,卖出委托：926.65
algo-1-vepgd_1  | 2019-08-07,卖出:
algo-1-vepgd_1  | 价格：929.79,                交易金额：115293.43,                手续费：23.06
algo-1-vepgd_1  | 2019-08-07,策略收益：
algo-1-vepgd_1  | 毛收益 -3096.35, 净收益 -3143.08
algo-1-vepgd_1  | 2019-08-13,买入委托：996.81
algo-1-vepgd_1  | 2019-08-14,交易失败
algo-1-vepgd_1  | 2019-08-14,买入委托：1021.67
algo-1-vepgd_1  | 2019-08-15,买入：
algo-1-vepgd_1  | 价格：1006.66,                交易金额：-113752.11,                手续费：22.75
algo-1-vepgd_1  | 2019-09-11,卖出委托：1047.31
algo-1-vepgd_1  | 2019-09-12,卖出:
algo-1-vepgd_1  | 价格：1043.87,                交易金额：117956.95,                手续费：23.59
algo-1-vepgd_1  | 2019-09-12,策略收益：
algo-1-vepgd_1  | 毛收益 4204.84, 净收益 4158.50
algo-1-vepgd_1  | 2019-09-20,买入委托：1133.39
algo-1-vepgd_1  | 2019-09-23,买入：
algo-1-vepgd_1  | 价格：1132.98,                交易金额：-120095.61,                手续费：24.02
algo-1-vepgd_1  | 2019-10-10,卖出委托：1131.02
algo-1-vepgd_1  | 2019-10-11,卖出:
algo-1-vepgd_1  | 价格：1132.98,                交易金额：120095.61,                手续费：24.02
algo-1-vepgd_1  | 2019-10-11,策略收益：
algo-1-vepgd_1  | 毛收益 0.00, 净收益 -48.04
algo-1-vepgd_1  | 2019-10-15,买入委托：1185.86
algo-1-vepgd_1  | 2019-10-16,买入：
algo-1-vepgd_1  | 价格：1143.75,                交易金额：-115518.65,                手续费：23.10
algo-1-vepgd_1  | 2019-10-23,卖出委托：1134.85
algo-1-vepgd_1  | 2019-10-24,卖出:
algo-1-vepgd_1  | 价格：1140.76,                交易金额：115217.00,                手续费：23.04
algo-1-vepgd_1  | 2019-10-24,策略收益：
algo-1-vepgd_1  | 毛收益 -301.65, 净收益 -347.80
algo-1-vepgd_1  | 2019-10-31,买入委托：1155.51
algo-1-vepgd_1  | 2019-11-01,买入：
algo-1-vepgd_1  | 价格：1156.48,                交易金额：-119117.35,                手续费：23.82
algo-1-vepgd_1  | 2019-11-26,卖出委托：1160.40
algo-1-vepgd_1  | 2019-11-27,卖出:
algo-1-vepgd_1  | 价格：1168.03,                交易金额：120307.52,                手续费：24.06
algo-1-vepgd_1  | 2019-11-27,策略收益：
algo-1-vepgd_1  | 毛收益 1190.16, 净收益 1142.28
algo-1-vepgd_1  | 2019-12-11,买入委托：1134.92
algo-1-vepgd_1  | 2019-12-12,买入：
algo-1-vepgd_1  | 价格：1132.00,                交易金额：-119991.81,                手续费：24.00
algo-1-vepgd_1  | 2019-12-25,卖出委托：1110.16
algo-1-vepgd_1  | 2019-12-26,卖出:
algo-1-vepgd_1  | 价格：1108.50,                交易金额：117500.63,                手续费：23.50
algo-1-vepgd_1  | 2019-12-26,策略收益：
algo-1-vepgd_1  | 毛收益 -2491.18, 净收益 -2538.68
algo-1-vepgd_1  | 2020-01-02,买入委托：1106.54
algo-1-vepgd_1  | 2020-01-03,买入：
algo-1-vepgd_1  | 价格：1093.81,                交易金额：-115943.64,                手续费：23.19
algo-1-vepgd_1  | 2020-01-03,卖出委托：1056.17
algo-1-vepgd_1  | 2020-01-06,卖出:
algo-1-vepgd_1  | 价格：1048.63,                交易金额：111154.35,                手续费：22.23
algo-1-vepgd_1  | 2020-01-06,策略收益：
algo-1-vepgd_1  | 毛收益 -4789.29, 净收益 -4834.71
algo-1-vepgd_1  | 2020-01-16,买入委托：1084.02
algo-1-vepgd_1  | 2020-01-17,买入：
algo-1-vepgd_1  | 价格：1086.95,                交易金额：-113043.14,                手续费：22.61
algo-1-vepgd_1  | 2020-01-21,卖出委托：1052.97
algo-1-vepgd_1  | 2020-01-22,卖出:
algo-1-vepgd_1  | 价格：1047.78,                交易金额：108969.52,                手续费：21.79
algo-1-vepgd_1  | 2020-01-22,策略收益：
algo-1-vepgd_1  | 毛收益 -4073.63, 净收益 -4118.03
algo-1-vepgd_1  | 2020-02-11,买入委托：1075.20
algo-1-vepgd_1  | 2020-02-12,买入：
algo-1-vepgd_1  | 价格：1066.39,                交易金额：-107705.32,                手续费：21.54
algo-1-vepgd_1  | 2020-02-28,卖出委托：1035.05
algo-1-vepgd_1  | 2020-03-02,卖出:
algo-1-vepgd_1  | 价格：1028.31,                交易金额：103858.98,                手续费：20.77
algo-1-vepgd_1  | 2020-03-02,策略收益：
algo-1-vepgd_1  | 毛收益 -3846.34, 净收益 -3888.65
algo-1-vepgd_1  | 2020-03-05,买入委托：1146.69
algo-1-vepgd_1  | 2020-03-06,买入：
algo-1-vepgd_1  | 价格：1138.85,                交易金额：-104774.46,                手续费：20.95
algo-1-vepgd_1  | 2020-03-16,卖出委托：1044.85
algo-1-vepgd_1  | 2020-03-17,卖出:
algo-1-vepgd_1  | 价格：1033.10,                交易金额：95044.76,                手续费：19.01
algo-1-vepgd_1  | 2020-03-17,策略收益：
algo-1-vepgd_1  | 毛收益 -9729.70, 净收益 -9769.66
algo-1-vepgd_1  | 2020-03-27,买入委托：1053.17
algo-1-vepgd_1  | 2020-03-30,买入：
algo-1-vepgd_1  | 价格：1038.24,                交易金额：-93441.26,                手续费：18.69
algo-1-vepgd_1  | 2020-06-15,卖出委托：1354.29
algo-1-vepgd_1  | 2020-06-16,卖出:
algo-1-vepgd_1  | 价格：1369.46,                交易金额：123251.69,                手续费：24.65
algo-1-vepgd_1  | 2020-06-16,策略收益：
algo-1-vepgd_1  | 毛收益 29810.43, 净收益 29767.09
algo-1-vepgd_1  | 2020-06-22,买入委托：1409.12
algo-1-vepgd_1  | 2020-06-23,买入：
algo-1-vepgd_1  | 价格：1405.21,                交易金额：-125063.28,                手续费：25.01
algo-1-vepgd_1  | 2020-07-21,卖出委托：1652.44
algo-1-vepgd_1  | 2020-07-22,卖出:
algo-1-vepgd_1  | 价格：1642.53,                交易金额：146185.60,                手续费：29.24
algo-1-vepgd_1  | 2020-07-22,策略收益：
algo-1-vepgd_1  | 毛收益 21122.32, 净收益 21068.08
algo-1-vepgd_1  | 2020-07-30,买入委托：1664.33
algo-1-vepgd_1  | 2020-07-31,交易失败
algo-1-vepgd_1  | 2020-08-03,买入委托：1652.44
algo-1-vepgd_1  | 2020-08-04,买入：
algo-1-vepgd_1  | 价格：1659.38,                交易金额：-146025.11,                手续费：29.21
algo-1-vepgd_1  | 2020-08-10,卖出委托：1618.75
algo-1-vepgd_1  | 2020-08-11,卖出:
algo-1-vepgd_1  | 价格：1624.70,                交易金额：142973.84,                手续费：28.59
algo-1-vepgd_1  | 2020-08-11,策略收益：
algo-1-vepgd_1  | 毛收益 -3051.27, 净收益 -3109.07
algo-1-vepgd_1  | 2020-08-18,买入委托：1689.10
algo-1-vepgd_1  | 2020-08-19,买入：
algo-1-vepgd_1  | 价格：1684.14,                交易金额：-141468.02,                手续费：28.29
algo-1-vepgd_1  | 2020-09-09,卖出委托：1672.26
algo-1-vepgd_1  | 2020-09-10,卖出:
algo-1-vepgd_1  | 价格：1687.85,                交易金额：141779.25,                手续费：28.36
algo-1-vepgd_1  | 2020-09-10,策略收益：
algo-1-vepgd_1  | 毛收益 311.23, 净收益 254.58
algo-1-vepgd_1  | 2020-09-18,买入委托：1679.19
algo-1-vepgd_1  | 2020-09-21,买入：
algo-1-vepgd_1  | 价格：1676.97,                交易金额：-142542.51,                手续费：28.51
algo-1-vepgd_1  | 2020-09-22,卖出委托：1650.15
algo-1-vepgd_1  | 2020-09-23,卖出:
algo-1-vepgd_1  | 价格：1619.75,                交易金额：137678.70,                手续费：27.54
algo-1-vepgd_1  | 2020-09-23,策略收益：
algo-1-vepgd_1  | 毛收益 -4863.81, 净收益 -4919.85
algo-1-vepgd_1  | 2020-10-12,买入委托：1734.28
algo-1-vepgd_1  | 2020-10-13,买入：
algo-1-vepgd_1  | 价格：1734.29,                交易金额：-138743.28,                手续费：27.75
algo-1-vepgd_1  | 2020-10-23,卖出委托：1699.33
algo-1-vepgd_1  | 2020-10-26,卖出:
algo-1-vepgd_1  | 价格：1603.90,                交易金额：128311.89,                手续费：25.66
algo-1-vepgd_1  | 2020-10-26,策略收益：
algo-1-vepgd_1  | 毛收益 -10431.38, 净收益 -10484.80
algo-1-vepgd_1  | 2020-11-05,买入委托：1705.84
algo-1-vepgd_1  | 2020-11-06,交易失败
algo-1-vepgd_1  | 2020-11-06,买入委托：1684.76
algo-1-vepgd_1  | 2020-11-09,买入：
algo-1-vepgd_1  | 价格：1685.51,                交易金额：-128098.78,                手续费：25.62
algo-1-vepgd_1  | 2020-11-18,卖出委托：1677.85
algo-1-vepgd_1  | 2020-11-19,卖出:
algo-1-vepgd_1  | 价格：1668.79,                交易金额：126827.86,                手续费：25.37
algo-1-vepgd_1  | 2020-11-19,策略收益：
algo-1-vepgd_1  | 毛收益 -1270.91, 净收益 -1321.90
algo-1-vepgd_1  | 2020-11-24,买入委托：1747.05
algo-1-vepgd_1  | 2020-11-25,买入：
algo-1-vepgd_1  | 价格：1745.07,                交易金额：-125645.00,                手续费：25.13
algo-1-vepgd_1  | 2020-12-02,卖出委托：1721.80
algo-1-vepgd_1  | 2020-12-03,卖出:
algo-1-vepgd_1  | 价格：1721.80,                交易金额：123969.50,                手续费：24.79
algo-1-vepgd_1  | 2020-12-03,策略收益：
algo-1-vepgd_1  | 毛收益 -1675.50, 净收益 -1725.43
algo-1-vepgd_1  | 2020-12-07,买入委托：1795.49
algo-1-vepgd_1  | 2020-12-08,买入：
algo-1-vepgd_1  | 价格：1798.07,                交易金额：-124066.86,                手续费：24.81
algo-1-vepgd_1  | 2021-01-20,卖出委托：2021.60
algo-1-vepgd_1  | 2021-01-21,卖出:
algo-1-vepgd_1  | 价格：2028.90,                交易金额：139993.90,                手续费：28.00
algo-1-vepgd_1  | 2021-01-21,策略收益：
algo-1-vepgd_1  | 毛收益 15927.04, 净收益 15874.23
algo-1-vepgd_1  | 2021-01-27,买入委托：2069.51
algo-1-vepgd_1  | 2021-01-28,买入：
algo-1-vepgd_1  | 价格：2060.60,                交易金额：-140120.71,                手续费：28.02
algo-1-vepgd_1  | 2021-02-25,卖出委托：2129.95
algo-1-vepgd_1  | 2021-02-26,卖出:
algo-1-vepgd_1  | 价格：2080.41,                交易金额：141468.02,                手续费：28.29
algo-1-vepgd_1  | 2021-02-26,策略收益：
algo-1-vepgd_1  | 毛收益 1347.31, 净收益 1291.00
algo-1-vepgd_1  | 2021-03-18,买入委托：2050.39
algo-1-vepgd_1  | 2021-03-19,买入：
algo-1-vepgd_1  | 价格：2016.02,                交易金额：-139105.27,                手续费：27.82
algo-1-vepgd_1  | 2021-03-25,卖出委托：1952.62
algo-1-vepgd_1  | 2021-03-26,卖出:
algo-1-vepgd_1  | 价格：1966.48,                交易金额：135687.45,                手续费：27.14
algo-1-vepgd_1  | 2021-03-26,策略收益：
algo-1-vepgd_1  | 毛收益 -3417.82, 净收益 -3472.78
algo-1-vepgd_1  | 2021-04-01,买入委托：2025.43
algo-1-vepgd_1  | 2021-04-02,买入：
algo-1-vepgd_1  | 价格：2036.82,                交易金额：-138503.93,                手续费：27.70
algo-1-vepgd_1  | 2021-04-13,卖出委托：2002.15
algo-1-vepgd_1  | 2021-04-14,卖出:
algo-1-vepgd_1  | 价格：2016.02,                交易金额：137089.25,                手续费：27.42
algo-1-vepgd_1  | 2021-04-14,策略收益：
algo-1-vepgd_1  | 毛收益 -1414.68, 净收益 -1469.80
algo-1-vepgd_1  | 2021-04-21,买入委托：2060.60
algo-1-vepgd_1  | 2021-04-22,买入：
algo-1-vepgd_1  | 价格：2070.41,                交易金额：-136646.82,                手续费：27.33
algo-1-vepgd_1  | 2021-04-30,卖出委托：1988.06
algo-1-vepgd_1  | 2021-05-06,卖出:
algo-1-vepgd_1  | 价格：1981.34,                交易金额：130768.76,                手续费：26.15
algo-1-vepgd_1  | 2021-05-06,策略收益：
algo-1-vepgd_1  | 毛收益 -5878.06, 净收益 -5931.54
algo-1-vepgd_1  | 2021-05-18,买入委托：2040.10
algo-1-vepgd_1  | 2021-05-19,买入：
algo-1-vepgd_1  | 价格：2039.79,                交易金额：-130546.85,                手续费：26.11
algo-1-vepgd_1  | 2021-06-09,卖出委托：2178.98
algo-1-vepgd_1  | 2021-06-10,卖出:
algo-1-vepgd_1  | 价格：2174.53,                交易金额：139169.66,                手续费：27.83
algo-1-vepgd_1  | 2021-06-10,策略收益：
algo-1-vepgd_1  | 毛收益 8622.81, 净收益 8568.87
algo-1-vepgd_1  | 2021-07-01,买入委托：2105.00
algo-1-vepgd_1  | 2021-07-02,买入：
algo-1-vepgd_1  | 价格：2075.00,                交易金额：-136950.00,                手续费：27.39
algo-1-vepgd_1  | 2021-07-05,(MA均线：  6日  11日) 期末总资金 134780.17
algo-1-vepgd_1  | Final Portfolio Value: 134780.17
algo-1-vepgd_1  | Return: 0.3478
tmppdbkowxv_algo-1-vepgd_1 exited with code 0
Aborting on container exit...
===== Job Complete =====

测试成功之后再将镜像推送到 ECR：

In [25]:
!docker tag {repository_name} {aws_account_id}.dkr.ecr.{aws_region}.amazonaws.com/{repository_name}
!docker images
!aws ecr get-login-password | docker login --username AWS --password-stdin {aws_account_id}.dkr.ecr.{aws_region}.amazonaws.com
!docker push {aws_account_id}.dkr.ecr.{aws_region}.amazonaws.com/{repository_name}

REPOSITORY                                                   TAG                 IMAGE ID            CREATED             SIZE
661060674358.dkr.ecr.us-east-1.amazonaws.com/sagemaker-hpo   latest              11ae0ba7d82c        4 minutes ago       1.07GB
sagemaker-hpo                                                latest              11ae0ba7d82c        4 minutes ago       1.07GB
python                                                       3.8                 1d136c1ca7e1        2 days ago          884MB
WARNING! Your password will be stored unencrypted in /home/ec2-user/.docker/config.json.
Configure a credential helper to remove this warning. See
https://docs.docker.com/engine/reference/commandline/login/#credentials-store

Login Succeeded
The push refers to repository [661060674358.dkr.ecr.us-east-1.amazonaws.com/sagemaker-hpo]

e7ac35ed: Preparing
f29e280e: Preparing
4537d80a: Preparing
b75c0b33: Preparing
02bf922a: Preparing
8fb65f84: Preparing
6c8cd771: Preparing
4df28046: Preparing
2e63bef3: Preparing
2f58daa9: Preparing
2d14a08f: Preparing
323e8881: Preparing
18ad7cad: Preparing
36d5a43a: Preparing
f0aa5c0a: Preparing
65095453: Preparing
db23340c: Preparing
36d5a43a: Pushed   520.8MB/510.1MBlatest: digest: sha256:0a8a9c4d1e9a51b936592e630895aa1ab15c21de98b3fe657654f963f24f44b9 size: 4088

### SageMaker 超参优化

接下来我们将定义一个超参优化任务。这首先，我们需要定义超参的类型和取值范围。在超参优化的过程中我们还需要定义一个目标参数（收益率）。SageMaker 将通过正则表达式从日志中提取目标参数所需的值，并判断最优的优化路径。这些配置信息通过 JSON 格式定义：

In [26]:
# 超参优化任务名称
from sagemaker.tuner import IntegerParameter, CategoricalParameter, ContinuousParameter, HyperparameterTuner

# 超参调优的参数配置
hyperparameter_ranges = {
    'fastmaperiod': IntegerParameter(5, 10),
    'slowmaperiod': IntegerParameter(10, 30),
}

# 目标参数的配置
metric_definitions = [
    {
        'Name': 'portfolio value', 
        'Regex': 'Final Portfolio Value: ([0-9\\.]+)'
    },
    {
        'Name': 'return', 
        'Regex': 'Return: ([0-9\\.]+)'
    }
]
objective_metric_name = "return"

In [27]:
estimator = Estimator(
    "{}.dkr.ecr.{}.amazonaws.com/{}".format(aws_account_id, aws_region, repository_name),
    role,
    train_instance_count=1,
    train_instance_type='ml.m5.2xlarge',
    output_path='s3://{}/{}/output'.format(bucket, repository_name),
    sagemaker_session=session
)

from sagemaker.tuner import HyperparameterTuner

tuner = HyperparameterTuner(
    estimator, 
    objective_metric_name,
    hyperparameter_ranges,
    metric_definitions=metric_definitions,
    strategy='Bayesian',
    objective_type='Maximize', 
    max_jobs=100,
    max_parallel_jobs=5,
    base_tuning_job_name=repository_name,
    early_stopping_type='Auto'
)

tuner.fit('s3://{}/{}/data.csv'.format(bucket, repository_name))

Parameter image_name will be renamed to image_uri in SageMaker Python SDK v2.
's3_input' class will be renamed to 'TrainingInput' in SageMaker Python SDK v2.

在超参优化任务结束之后，我们可以通过以下将结果加载到一个 DataFrame 中，并随时查看优化的结果：

In [28]:
tuner_analytics = tuner.analytics()
tuning_result = tuner_analytics.dataframe().sort_values(['FinalObjectiveValue'], ascending=False)
tuning_result.head(10)

,fastmaperiod,slowmaperiod,TrainingJobName,TrainingJobStatus,FinalObjectiveValue,TrainingStartTime,TrainingEndTime,TrainingElapsedTimeSeconds
5,7.0,22.0,sagemaker-hpo-210809-0013-005-78e31cba,Completed,1.0040,2021-08-09 00:15:51+00:00,2021-08-09 00:16:46+00:00,55.0
8,9.0,19.0,sagemaker-hpo-210809-0013-002-83373bd1,Completed,0.9634,2021-08-09 00:15:41+00:00,2021-08-09 00:16:43+00:00,62.0
6,6.0,30.0,sagemaker-hpo-210809-0013-004-9e9ac4a1,Completed,0.8997,2021-08-09 00:15:59+00:00,2021-08-09 00:16:57+00:00,58.0
7,5.0,15.0,sagemaker-hpo-210809-0013-003-0b0f26eb,Completed,0.7914,2021-08-09 00:15:42+00:00,2021-08-09 00:16:33+00:00,51.0
9,10.0,27.0,sagemaker-hpo-210809-0013-001-9dbd0abe,Completed,0.6990,2021-08-09 00:15:38+00:00,2021-08-09 00:16:31+00:00,53.0
0,6.0,21.0,sagemaker-hpo-210809-0013-010-4a1dcb48,InProgress,NaN,NaT,NaT,NaN
1,5.0,22.0,sagemaker-hpo-210809-0013-009-cce53090,InProgress,NaN,NaT,NaT,NaN
2,6.0,22.0,sagemaker-hpo-210809-0013-008-5516b261,InProgress,NaN,NaT,NaT,NaN
3,9.0,20.0,sagemaker-hpo-210809-0013-007-02797bb4,InProgress,NaN,NaT,NaT,NaN
4,7.0,20.0,sagemaker-hpo-210809-0013-006-74268cdc,InProgress,NaN,NaT,NaT,NaN

可以观察下 SageMaker 是否很快就找到了最优参数组合呢？您可以将均线范围再扩大些，看看 SageMaker HPO 在实验组数更多的时候是否效果会比网格搜索更好